### ISSUE TITLE
wrapping text strings in P tags instead of BR

### ISSUE THREAD

**Issue by rogerlherbert** [milesj/decoda#12]
Thanks for this, it's very handy.

My one issue so far is that it returns all newlines in the text with BR tags, where I'd prefer it to wrap the string in P tags at each break, so instead of this:

```
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
<br>
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
<br>
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
```

I'd like this:

```
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
<p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p>
```

Suggestions welcome!

**Comment by 0815Neo** [comment]
Maybe you should think about an additional option. I have currently a use case that causes that our design is broken.

I want to wrap a "p" tag around the parsed bbcode to apply the paragraph design. The problem is the following bbcode:

    Hello World!
    [list]
      [*] Item 1
      [*] Item 2

Output the following html

    Hello World!<ul><li>Item 1</li><li>Item 2</li></ul>

I can´t put a 'p' tag around this content because the following Code would be invalid:

    <p>Hello World!<ul><li>Item 1</li><li>Item 2</li></ul></p>
