### ISSUE TITLE
bbcode problem

### ISSUE THREAD

**Issue by toinouu** [milesj/decoda#95]
This code 
```javascript
[b]qsdqsdqsdqsdqsdqsdqsdqsdsqd

[/b]qsdqsdqsdqsdqsd
```
should display

__qsdqsdqsdqsdqsdqsdqsdqsdsqd__

qsdqsdqsdqsdqsd

it appears that

**qsdqsdqsdqsdqsdqsdqsdqsdsqd**qsdqsdqsdqsdqsd

there is same problem with other bbcode

**Comment by milesj** [comment]
I'm pretty sure I `trim()` the contents between tags. This is required for certain filters to work and I doubt I will change it.

**Comment by alquerci** [comment]
This issue is related to #63 but in that case for newlines. These issues blame the commit 01c690c9d94824cae5ebdaf32c9c63a459e9dac8 that fixed issue #50.

So I am of the same opinion as @connor4312 on https://github.com/milesj/decoda/pull/63#issuecomment-35121425
> I think removing the `trim` would indeed be a better solution

A fix for #50 should be alquerci/decoda@eb8571ab2b9c2bddc67ac727764a924de3193ff2.

**Comment by milesj** [comment]
I'll have to look into the code again. Been a really long time since I've used it.

**Comment by milesj** [comment]
Removed the trim all together.
